In [2]:
import os

os.getcwd()

'/media/hamza/Disque local1/Hamza Bouajila/Portfolio/Building-a-Batch-ETL-Pipeline-RedPanda/notebooks'

In [3]:
os.chdir("../")
os.getcwd()

'/media/hamza/Disque local1/Hamza Bouajila/Portfolio/Building-a-Batch-ETL-Pipeline-RedPanda'

In [4]:
from data_pipeline.src.core.config import settings
import duckdb

# Initiate a MotherDuck connection using an access token
con = duckdb.connect(f"md:StreamingApp?motherduck_token={settings.MOTHERDUCK_TOKEN}")

In [5]:
con

In [6]:
con.sql("SHOW DATABASES").show()

┌───────────────────────┐
│     database_name     │
│        varchar        │
├───────────────────────┤
│ StreamingApp          │
│ md_information_schema │
│ my_db                 │
│ sample_data           │
└───────────────────────┘

In [7]:
con.sql("SELECT current_database()").fetchdf()

  current_database()
0       StreamingApp

In [8]:
con.sql("USE main")

In [9]:
con.sql("SELECT current_database()").fetchdf()

  current_database()
0       StreamingApp

In [10]:
con.sql("SHOW TABLES")

┌─────────────┐
│    name     │
│   varchar   │
├─────────────┤
│ BitcoinData │
└─────────────┘

In [17]:
# Check if table exists
table_name = "Coin"
table_exists = (
    con.sql(
        f"SELECT COUNT(*) FROM information_schema.tables WHERE table_name = '{table_name}'"
    ).fetchone()[0]
    > 0
)

if not table_exists:
    # Create table if it does not exist
    con.sql(f"CREATE TABLE {table_name} (column1 VARCHAR, column2 VARCHAR)")

# Insert data into the table
con.sql(f"INSERT INTO {table_name} VALUES ('value1', 'value2')")

In [11]:
con.sql("""
            CREATE TABLE IF NOT EXISTS BitcoinData (
                price VARCHAR(255),
                volume_24h VARCHAR(255),
                volume_change_24h VARCHAR(255),
                percent_change_1h VARCHAR(255),
                percent_change_24h VARCHAR(255),
                percent_change_7d VARCHAR(255),
                market_cap VARCHAR(255),
                market_cap_dominance VARCHAR(255),
                fully_diluted_market_cap VARCHAR(255),
                last_updated VARCHAR(255)
            );
        """)

In [14]:
doc = {
    "title": "Can Bangladesh and India transcend South Asia colonial legacies?",
    "description": "broader question whether south asia transcend legacy colonialism embrace model cooperation prioritises collective wellbeing individual dominance",
    "pubDate": "2025-01-03 06:00:00",
    "source": "The Daily Star",
}

In [15]:
con.sql(
    f"""INSERT INTO NewsData (description, source, pubDate, title)
    VALUES (
    '{doc["description"]}',
    '{doc["source"]}',
    '{doc["pubDate"]}',
    '{doc["title"]}'
)
    """
)

In [9]:
con.sql("SELECT * FROM BitcoinData").df().price.unique()

array(['0.4215114194292098', '0.7780522780411343', '0.13189954831071105',
       '0.5255553606130763', '0.6757473744895182', '0.6223777678136049',
       '0.9841970170202479', '0.2691539847094122', '0.27855233190683304',
       '0.8732501937647683'], dtype=object)

In [19]:
raw_data = b'[{"price":0.8629895161668029,"volume_24h":6123,"volume_change_24h":0.6976767716483763,"percent_change_1h":0.46812121270035467,"percent_change_24h":0.18196343437283402,"percent_change_7d":0.09957471501271642,"market_cap":0.8008555150233527,"market_cap_dominance":9575,"fully_diluted_market_cap":0.38517646246467874,"last_updated":"2025-01-12T12:51:36.786Z","id":7686},{"price":0.3505522771490943,"volume_24h":1229,"volume_change_24h":0.07658294835942625,"percent_change_1h":0.6556305490590719,"percent_change_24h":0.7562916827475383,"percent_change_7d":0.7979807453293117,"market_cap":0.4267671557985979,"market_cap_dominance":5061,"fully_diluted_market_cap":0.7418150087889359,"last_updated":"2025-01-12T12:51:36.786Z","id":2653},{"price":0.7479435871735649,"volume_24h":2122,"volume_change_24h":0.9586294276457037,"percent_change_1h":0.46139892434344665,"percent_change_24h":0.42524205877710064,"percent_change_7d":0.14845922438682413,"market_cap":0.9654217650968471,"market_cap_dominance":6863,"fully_diluted_market_cap":0.4528408253011924,"last_updated":"2025-01-12T12:51:36.786Z","id":5932},{"price":0.3891842981147282,"volume_24h":176,"volume_change_24h":0.6816866143367024,"percent_change_1h":0.825579461470439,"percent_change_24h":0.7933963196229912,"percent_change_7d":0.7617869206029739,"market_cap":0.5343555811922576,"market_cap_dominance":1960,"fully_diluted_market_cap":0.8184279703468629,"last_updated":"2025-01-12T12:51:36.786Z","id":6209},{"price":0.6926194772344223,"volume_24h":5667,"volume_change_24h":0.9208923335565147,"percent_change_1h":0.7293216884625666,"percent_change_24h":0.5655543514354322,"percent_change_7d":0.9301576336768176,"market_cap":0.5379676778955278,"market_cap_dominance":6334,"fully_diluted_market_cap":0.2839642032698553,"last_updated":"2025-01-12T12:51:36.786Z","id":477},{"price":0.7200376310029206,"volume_24h":7933,"volume_change_24h":0.12769381142557523,"percent_change_1h":0.09141898006725446,"percent_change_24h":0.41886834657155725,"percent_change_7d":0.6146471356122638,"market_cap":0.013287300720147499,"market_cap_dominance":7837,"fully_diluted_market_cap":0.061234446434405454,"last_updated":"2025-01-12T12:51:36.786Z","id":983},{"price":0.1250298808428698,"volume_24h":9582,"volume_change_24h":0.8586958714334283,"percent_change_1h":0.6470931224253886,"percent_change_24h":0.9964744455289114,"percent_change_7d":0.22233037759292307,"market_cap":0.922159453796783,"market_cap_dominance":6081,"fully_diluted_market_cap":0.86649711915216,"last_updated":"2025-01-12T12:51:36.786Z","id":8853},{"price":0.4400201456031767,"volume_24h":4037,"volume_change_24h":0.42371469528379024,"percent_change_1h":0.12087048118418786,"percent_change_24h":0.009880237307622997,"percent_change_7d":0.7393585001996974,"market_cap":0.7895652604669756,"market_cap_dominance":8418,"fully_diluted_market_cap":0.06259525457695725,"last_updated":"2025-01-12T12:51:36.786Z","id":3015},{"price":0.9618362605447246,"volume_24h":6855,"volume_change_24h":0.6807578760270483,"percent_change_1h":0.8693178741718677,"percent_change_24h":0.19553211460132403,"percent_change_7d":0.08038377392501062,"market_cap":0.9413654610528082,"market_cap_dominance":9623,"fully_diluted_market_cap":0.2613183577811953,"last_updated":"2025-01-12T12:51:36.786Z","id":8123},{"price":0.43289883570149046,"volume_24h":2585,"volume_change_24h":0.06756070149347715,"percent_change_1h":0.44042457819435876,"percent_change_24h":0.5955287187837481,"percent_change_7d":0.0716099714014149,"market_cap":0.631307383876555,"market_cap_dominance":1498,"fully_diluted_market_cap":0.679210682473089,"last_updated":"2025-01-12T12:51:36.786Z","id":5416}]'

In [20]:
import json


def clean_data(raw_data: bytes | list) -> list:
    if isinstance(raw_data, list):
        return raw_data
    data_str = raw_data.decode("utf-8")
    json_data = json.loads(data_str)

    return json_data

In [26]:
import uuid

record = clean_data(raw_data)
for doc in record:
    print(f"Loading document: {doc}")
    doc["id"] = uuid.uuid4().hex
    con.sql(
        f"""INSERT INTO BitcoinData (id, price, volume_24h, volume_change_24h, percent_change_1h, percent_change_24h, percent_change_7d, market_cap, market_cap_dominance, fully_diluted_market_cap, last_updated)
        VALUES (
        '{doc["id"]}',
        '{doc["price"]}',
        '{doc["volume_24h"]}',
        '{doc["volume_change_24h"]}',
        '{doc["percent_change_1h"]}',
        '{doc["percent_change_24h"]}',
        '{doc["percent_change_7d"]}',
        '{doc["market_cap"]}',
        '{doc["market_cap_dominance"]}',
        '{doc["fully_diluted_market_cap"]}',
        '{doc["last_updated"]}'
    )
        """
    )
    print("Data loaded successfully")

Loading document: {'price': 0.8629895161668029, 'volume_24h': 6123, 'volume_change_24h': 0.6976767716483763, 'percent_change_1h': 0.46812121270035467, 'percent_change_24h': 0.18196343437283402, 'percent_change_7d': 0.09957471501271642, 'market_cap': 0.8008555150233527, 'market_cap_dominance': 9575, 'fully_diluted_market_cap': 0.38517646246467874, 'last_updated': '2025-01-12T12:51:36.786Z', 'id': 7686}
Data loaded successfully
Loading document: {'price': 0.3505522771490943, 'volume_24h': 1229, 'volume_change_24h': 0.07658294835942625, 'percent_change_1h': 0.6556305490590719, 'percent_change_24h': 0.7562916827475383, 'percent_change_7d': 0.7979807453293117, 'market_cap': 0.4267671557985979, 'market_cap_dominance': 5061, 'fully_diluted_market_cap': 0.7418150087889359, 'last_updated': '2025-01-12T12:51:36.786Z', 'id': 2653}
Data loaded successfully
Loading document: {'price': 0.7479435871735649, 'volume_24h': 2122, 'volume_change_24h': 0.9586294276457037, 'percent_change_1h': 0.46139892434344665, 'percent_change_24h': 0.42524205877710064, 'percent_change_7d': 0.14845922438682413, 'market_cap': 0.9654217650968471, 'market_cap_dominance': 6863, 'fully_diluted_market_cap': 0.4528408253011924, 'last_updated': '2025-01-12T12:51:36.786Z', 'id': 5932}
Data loaded successfully
Loading document: {'price': 0.3891842981147282, 'volume_24h': 176, 'volume_change_24h': 0.6816866143367024, 'percent_change_1h': 0.825579461470439, 'percent_change_24h': 0.7933963196229912, 'percent_change_7d': 0.7617869206029739, 'market_cap': 0.5343555811922576, 'market_cap_dominance': 1960, 'fully_diluted_market_cap': 0.8184279703468629, 'last_updated': '2025-01-12T12:51:36.786Z', 'id': 6209}
Data loaded successfully
Loading document: {'price': 0.6926194772344223, 'volume_24h': 5667, 'volume_change_24h': 0.9208923335565147, 'percent_change_1h': 0.7293216884625666, 'percent_change_24h': 0.5655543514354322, 'percent_change_7d': 0.9301576336768176, 'market_cap': 0.5379676778955278, 'market_cap_dominance': 6334, 'fully_diluted_market_cap': 0.2839642032698553, 'last_updated': '2025-01-12T12:51:36.786Z', 'id': 477}
Data loaded successfully
Loading document: {'price': 0.7200376310029206, 'volume_24h': 7933, 'volume_change_24h': 0.12769381142557523, 'percent_change_1h': 0.09141898006725446, 'percent_change_24h': 0.41886834657155725, 'percent_change_7d': 0.6146471356122638, 'market_cap': 0.013287300720147499, 'market_cap_dominance': 7837, 'fully_diluted_market_cap': 0.061234446434405454, 'last_updated': '2025-01-12T12:51:36.786Z', 'id': 983}
Data loaded successfully
Loading document: {'price': 0.1250298808428698, 'volume_24h': 9582, 'volume_change_24h': 0.8586958714334283, 'percent_change_1h': 0.6470931224253886, 'percent_change_24h': 0.9964744455289114, 'percent_change_7d': 0.22233037759292307, 'market_cap': 0.922159453796783, 'market_cap_dominance': 6081, 'fully_diluted_market_cap': 0.86649711915216, 'last_updated': '2025-01-12T12:51:36.786Z', 'id': 8853}
Data loaded successfully
Loading document: {'price': 0.4400201456031767, 'volume_24h': 4037, 'volume_change_24h': 0.42371469528379024, 'percent_change_1h': 0.12087048118418786, 'percent_change_24h': 0.009880237307622997, 'percent_change_7d': 0.7393585001996974, 'market_cap': 0.7895652604669756, 'market_cap_dominance': 8418, 'fully_diluted_market_cap': 0.06259525457695725, 'last_updated': '2025-01-12T12:51:36.786Z', 'id': 3015}
Data loaded successfully
Loading document: {'price': 0.9618362605447246, 'volume_24h': 6855, 'volume_change_24h': 0.6807578760270483, 'percent_change_1h': 0.8693178741718677, 'percent_change_24h': 0.19553211460132403, 'percent_change_7d': 0.08038377392501062, 'market_cap': 0.9413654610528082, 'market_cap_dominance': 9623, 'fully_diluted_market_cap': 0.2613183577811953, 'last_updated': '2025-01-12T12:51:36.786Z', 'id': 8123}
Data loaded successfully
Loading document: {'price': 0.43289883570149046, 'volume_24h': 2585, 'volume_change_24h': 0.06756070149347715, 'percent_change_1h': 0.44042457819435876, 'percent_change_24h': 0.5955287187837481, 'percent_change_7d': 0.0716099714014149, 'market_cap': 0.631307383876555, 'market_cap_dominance': 1498, 'fully_diluted_market_cap': 0.679210682473089, 'last_updated': '2025-01-12T12:51:36.786Z', 'id': 5416}
Data loaded successfully

In [18]:
print(record)

[b'[{"price":0.8629895161668029,"volume_24h":6123,"volume_change_24h":0.6976767716483763,"percent_change_1h":0.46812121270035467,"percent_change_24h":0.18196343437283402,"percent_change_7d":0.09957471501271642,"market_cap":0.8008555150233527,"market_cap_dominance":9575,"fully_diluted_market_cap":0.38517646246467874,"last_updated":"2025-01-12T12:51:36.786Z","id":7686},{"price":0.3505522771490943,"volume_24h":1229,"volume_change_24h":0.07658294835942625,"percent_change_1h":0.6556305490590719,"percent_change_24h":0.7562916827475383,"percent_change_7d":0.7979807453293117,"market_cap":0.4267671557985979,"market_cap_dominance":5061,"fully_diluted_market_cap":0.7418150087889359,"last_updated":"2025-01-12T12:51:36.786Z","id":2653},{"price":0.7479435871735649,"volume_24h":2122,"volume_change_24h":0.9586294276457037,"percent_change_1h":0.46139892434344665,"percent_change_24h":0.42524205877710064,"percent_change_7d":0.14845922438682413,"market_cap":0.9654217650968471,"market_cap_dominance":6863,"fully_diluted_market_cap":0.4528408253011924,"last_updated":"2025-01-12T12:51:36.786Z","id":5932},{"price":0.3891842981147282,"volume_24h":176,"volume_change_24h":0.6816866143367024,"percent_change_1h":0.825579461470439,"percent_change_24h":0.7933963196229912,"percent_change_7d":0.7617869206029739,"market_cap":0.5343555811922576,"market_cap_dominance":1960,"fully_diluted_market_cap":0.8184279703468629,"last_updated":"2025-01-12T12:51:36.786Z","id":6209},{"price":0.6926194772344223,"volume_24h":5667,"volume_change_24h":0.9208923335565147,"percent_change_1h":0.7293216884625666,"percent_change_24h":0.5655543514354322,"percent_change_7d":0.9301576336768176,"market_cap":0.5379676778955278,"market_cap_dominance":6334,"fully_diluted_market_cap":0.2839642032698553,"last_updated":"2025-01-12T12:51:36.786Z","id":477},{"price":0.7200376310029206,"volume_24h":7933,"volume_change_24h":0.12769381142557523,"percent_change_1h":0.09141898006725446,"percent_change_24h":0.41886834657155725,"percent_change_7d":0.6146471356122638,"market_cap":0.013287300720147499,"market_cap_dominance":7837,"fully_diluted_market_cap":0.061234446434405454,"last_updated":"2025-01-12T12:51:36.786Z","id":983},{"price":0.1250298808428698,"volume_24h":9582,"volume_change_24h":0.8586958714334283,"percent_change_1h":0.6470931224253886,"percent_change_24h":0.9964744455289114,"percent_change_7d":0.22233037759292307,"market_cap":0.922159453796783,"market_cap_dominance":6081,"fully_diluted_market_cap":0.86649711915216,"last_updated":"2025-01-12T12:51:36.786Z","id":8853},{"price":0.4400201456031767,"volume_24h":4037,"volume_change_24h":0.42371469528379024,"percent_change_1h":0.12087048118418786,"percent_change_24h":0.009880237307622997,"percent_change_7d":0.7393585001996974,"market_cap":0.7895652604669756,"market_cap_dominance":8418,"fully_diluted_market_cap":0.06259525457695725,"last_updated":"2025-01-12T12:51:36.786Z","id":3015},{"price":0.9618362605447246,"volume_24h":6855,"volume_change_24h":0.6807578760270483,"percent_change_1h":0.8693178741718677,"percent_change_24h":0.19553211460132403,"percent_change_7d":0.08038377392501062,"market_cap":0.9413654610528082,"market_cap_dominance":9623,"fully_diluted_market_cap":0.2613183577811953,"last_updated":"2025-01-12T12:51:36.786Z","id":8123},{"price":0.43289883570149046,"volume_24h":2585,"volume_change_24h":0.06756070149347715,"percent_change_1h":0.44042457819435876,"percent_change_24h":0.5955287187837481,"percent_change_7d":0.0716099714014149,"market_cap":0.631307383876555,"market_cap_dominance":1498,"fully_diluted_market_cap":0.679210682473089,"last_updated":"2025-01-12T12:51:36.786Z","id":5416}]']